name: enum_extension
description: enum extension
version: 0.1.0+1
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer:
  build:
  build_config:
  enum_extension_annotation:
    path: ../enum_extension_annotation
  source_gen:

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
