name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  enum_extension_annotation:
    path: ..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  enum_extension:
    path: ../../enum_extension
  build_runner:
